In [2]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/home/zodiac/miniconda3/lib/python3.8/site-packages/tensorflow/_api/v2/version/__init__.py'>


In [4]:
a = tf.constant([2], name = 'constant_a')
b = tf.constant([3], name = 'constant_b')

In [5]:
tf.print(a.numpy()[0])

2


In [7]:
@tf.function
def add(a,b):
    c = tf.add(a, b)
    #c = a + b is also a way to define the sum of the terms
    print(c)
    return c

In [8]:
result = add(a,b)
tf.print(result[0])

Tensor("Add:0", shape=(1,), dtype=int32)
5


In [9]:
result

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([5], dtype=int32)>

In TensorFlow all data is passed between operations in a computation graph, and these are passed in the form of Tensors, hence the name of TensorFlow.

In [10]:
scalar = tf.constant(2)
vector = tf.constant([5,6,2])
matrix = tf.constant([[1,2,3], [2,3,4], [4,5,6]])
tensor = tf.constant([ [[1,2],[2,3],[3,4]], [[1,2],[2,3],[3,4]],[[1,2],[2,3],[3,4]] ])

print("scalar : \n %s \n"%scalar)
print("vector : \n %s \n"%vector)
print("matrix : \n %s \n"%matrix)
print("tensor : \n %s \n"%tensor)

scalar : 
 tf.Tensor(2, shape=(), dtype=int32) 

vector : 
 tf.Tensor([5 6 2], shape=(3,), dtype=int32) 

matrix : 
 tf.Tensor(
[[1 2 3]
 [2 3 4]
 [4 5 6]], shape=(3, 3), dtype=int32) 

tensor : 
 tf.Tensor(
[[[1 2]
  [2 3]
  [3 4]]

 [[1 2]
  [2 3]
  [3 4]]

 [[1 2]
  [2 3]
  [3 4]]], shape=(3, 3, 2), dtype=int32) 



In [11]:
matrix.shape

TensorShape([3, 3])

In [12]:
one = tf.constant([ [1,2,3], [1,2,3], [3,2,1]])
print(one.shape)
two = tf.constant([ [1,1,1], [2,2,2], [3,3,3]])
print(two.shape)

tf.function
def add():
    result = one+two
    return result

lol = add()
print("\n",lol)

(3, 3)
(3, 3)

 tf.Tensor(
[[2 3 4]
 [3 4 5]
 [6 5 4]], shape=(3, 3), dtype=int32)


In [13]:
one = tf.constant([[1,2], [2,3]])
two = tf.constant([[2,2], [2,2]])

@tf.function
def multiplyMat():
    return tf.matmul(one, two)

@tf.function
def neww():
    return one*two

mul = multiplyMat()
print(mul,'\n\n')


mul = neww()
print(mul)

tf.Tensor(
[[ 6  6]
 [10 10]], shape=(2, 2), dtype=int32) 


tf.Tensor(
[[2 4]
 [4 6]], shape=(2, 2), dtype=int32)


In [14]:
v = tf.Variable(0)

@tf.function
def increment(v):
    v=v+1
    #v = tf.add(v,1)
    return v

for i in range(3):
    v = increment(v)
    print(v)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


zx znz

shortcuts 
a,b - add cells
d - delete cells
m - markdown
?? - documentation of function 